# Site settings
title: Christian Herrera
description: 'Estudiante Ingenieria en Computacion'
url: 'https://chrisrp.com'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Christian Herrera'
  email: chris1496.rp@gmail.com
  twitter_username: chriissrp
#  facebook_username: joshgerdes
  github_username:  christian-herrera
  linkedin_username:  
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
